name: detection_app
description: "An app to detect lechmaniasis"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  file: ^7.0.0

  flutter_localizations:
    sdk: flutter
  
  intl: ^0.19.0

  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.2

  model_viewer_plus: ^1.7.0

  camera: ^0.10.0+4

  path_provider: ^2.0.15

  image_picker: ^1.1.2

  file_picker: ^8.1.2

  share_plus: ^10.0.2

  hive: ^2.2.3

  hive_flutter: ^1.1.0

  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/
